name: VTest CI

on:
  # Run on events
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# A bunch of tasks to do
jobs:
  build:
    # Runner
    runs-on: ubuntu-latest
    # Actions
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Run lint checks
        run: ./gradlew lint